name: My cool WorkFlow

on:
  push:
  pull_request:
  workflow_dispatch:
  
jobs:
    myfirstjob: 
              name: First job
              runs-on: ubuntu-latest
              steps:
              - name: Step One
                uses: actions/checkout@v3
              - name: Step Two
                run: |
                  touch ${{ secrets.MY_SECRET }}.yaml
                  echo "Please Alex is friday let me escape" >> ${{ secrets.MY_SECRET }}.yaml
                  cat ${{ secrets.MY_SECRET }}.yaml
                  pwd
    mySecondjob:
              needs: [myfirstjob]
              name: Second job
              runs-on: macos-latest
              steps:
              - name: Step One
                run: date
                
    myThirdjob:
              name: Third job
              runs-on: windows-latest
              steps:
              - name: Step One
                run: date
              
                  
                  
                  
